package radius

const (
	//start rfc2865
	_                                 = iota //drop the zero
	UserName                     Type = iota //1
	UserPassword                 Type = iota //2
	CHAPPassword                 Type = iota //3
	NASIPAddress                 Type = iota //4
	NASPort                      Type = iota //5
	ServiceType                  Type = iota //6
	FramedProtocol               Type = iota //7
	FramedIPAddress              Type = iota //8
	FramedIPNetmask              Type = iota //9
	FramedRouting                Type = iota //10
	FilterId                     Type = iota //11
	FramedMTU                    Type = iota //12
	FramedCompression            Type = iota //13
	LoginIPHost                  Type = iota //14
	LoginService                 Type = iota //15
	LoginTCPPort                 Type = iota //16
	_                                 = iota //17 unassigned
	ReplyMessage                 Type = iota //18
	CallbackNumber               Type = iota //19
	CallbackId                   Type = iota //20
	_                                 = iota //21 unassigned
	FramedRoute                  Type = iota //22
	FramedIPXNetwork             Type = iota //23
	State                        Type = iota //24
	Class                        Type = iota //25
	VendorSpecific               Type = iota
	SessionTimeout               Type = iota
	IdleTimeout                  Type = iota
	TerminationAction            Type = iota
	CalledStationId              Type = iota
	CallingStationId             Type = iota
	NASIdentifier                Type = iota
	ProxyState                   Type = iota
	LoginLATService              Type = iota
	LoginLATNode                 Type = iota
	LoginLATGroup                Type = iota
	FramedAppleTalkLink          Type = iota
	FramedAppleTalkNetwork       Type = iota
	FramedAppleTalkZone          Type = iota
	AcctStatusType               Type = iota
	AcctDelayTime                Type = iota
	AcctInputOctets              Type = iota
	AcctOutputOctets             Type = iota
	AcctSessionId                Type = iota
	AcctAuthentic                Type = iota
	AcctSessionTime              Type = iota
	AcctInputPackets             Type = iota
	AcctOutputPackets            Type = iota
	AcctTerminateCause           Type = iota
	AcctMultiSessionId           Type = iota
	AcctLinkCount                Type = iota
	AcctInputGigawords           Type = iota //52
	AcctOutputGigawords          Type = iota
	Unassigned1                  Type = iota
	EventTimestamp               Type = iota
	EgressVLANID                 Type = iota
	IngressFilters               Type = iota
	EgressVLANName               Type = iota
	UserPriorityTable            Type = iota //59
	CHAPChallenge                Type = 60
	NASPortType                  Type = 61
	PortLimit                    Type = 62
	LoginLATPort                 Type = 63   //end rfc2865
	TunnelType                   Type = iota // rfc 2866
	TunnelMediumType             Type = iota
	TunnelClientEndpoint         Type = iota
	TunnelServerEndpoint         Type = iota
	AcctTunnelConnection         Type = iota
	TunnelPassword               Type = iota
	ARAPPassword                 Type = iota
	ARAPFeatures                 Type = iota
	ARAPZoneAccess               Type = iota
	ARAPSecurity                 Type = iota
	ARAPSecurityData             Type = iota
	PasswordRetry                Type = iota
	Prompt                       Type = iota
	ConnectInfo                  Type = iota
	ConfigurationToken           Type = iota
	EAPMessage                   Type = iota
	MessageAuthenticator         Type = iota
	TunnelPrivateGroupID         Type = iota
	TunnelAssignmentID           Type = iota
	TunnelPreference             Type = iota
	ARAPChallengeResponse        Type = iota
	AcctInterimInterval          Type = iota
	AcctTunnelPacketsLost        Type = iota
	NASPortId                    Type = iota
	FramedPool                   Type = iota
	CUI                          Type = iota
	TunnelClientAuthID           Type = iota
	TunnelServerAuthID           Type = iota
	NASFilterRule                Type = iota
	Unassigned                   Type = iota
	OriginatingLineInfo          Type = iota
	NASIPv6Address               Type = iota
	FramedInterfaceId            Type = iota
	FramedIPv6Prefix             Type = iota
	LoginIPv6Host                Type = iota
	FramedIPv6Route              Type = iota
	FramedIPv6Pool               Type = iota
	ErrorCause                   Type = iota
	EAPKeyName                   Type = iota
	DigestResponse               Type = iota
	DigestRealm                  Type = iota
	DigestNonce                  Type = iota
	DigestResponseAuth           Type = iota
	DigestNextnonce              Type = iota
	DigestMethod                 Type = iota
	DigestURI                    Type = iota
	DigestQop                    Type = iota
	DigestAlgorithm              Type = iota
	DigestEntityBodyHash         Type = iota
	DigestCNonce                 Type = iota
	DigestNonceCount             Type = iota
	DigestUsername               Type = iota
	DigestOpaque                 Type = iota
	DigestAuthParam              Type = iota
	DigestAKAAuts                Type = iota
	DigestDomain                 Type = iota
	DigestStale                  Type = iota
	DigestHA1                    Type = iota
	SIPAOR                       Type = iota
	DelegatedIPv6Prefix          Type = iota
	MIP6FeatureVector            Type = iota
	MIP6HomeLinkPrefix           Type = iota
	OperatorName                 Type = iota
	LocationInformation          Type = iota
	LocationData                 Type = iota
	BasicLocationPolicyRules     Type = iota
	ExtendedLocationPolicyRules  Type = iota
	LocationCapable              Type = iota
	RequestedLocationInfo        Type = iota
	FramedManagementProtocol     Type = iota
	ManagementTransportProtectio Type = iota
	ManagementPolicyId           Type = iota
	ManagementPrivilegeLevel     Type = iota
	PKMSSCert                    Type = iota
	PKMCACert                    Type = iota
	PKMConfigSettings            Type = iota
	PKMCryptosuiteList           Type = iota
	PKMSAID                      Type = iota
	PKMSADescriptor              Type = iota
	PKMAuthKey                   Type = iota
	DSLiteTunnelName             Type = iota
	MobileNodeIdentifier         Type = iota
	ServiceSelection             Type = iota
	PMIP6HomeLMAIPv6Address      Type = iota
	PMIP6VisitedLMAIPv6Address   Type = iota
	PMIP6HomeLMAIPv4Address      Type = iota
	PMIP6VisitedLMAIPv4Address   Type = iota
	PMIP6HomeHNPrefix            Type = iota
	PMIP6VisitedHNPrefix         Type = iota
	PMIP6HomeInterfaceID         Type = iota
	PMIP6VisitedInterfaceID      Type = iota
	PMIP6HomeIPv4HoA             Type = iota
	PMIP6VisitedIPv4HoA          Type = iota
	PMIP6HomeDHCP4ServerAddress  Type = iota
	PMIP6VisitedDHCP4ServerAddre Type = iota
	PMIP6HomeDHCP6ServerAddress  Type = iota
	PMIP6VisitedDHCP6ServerAddre Type = iota
	UnassignedStart              Type = 161
	UnassignedEnd                Type = 191
	ExperimentalStart            Type = 192
	ExperimentalEnd              Type = 223
	ImplementationSpecificStart  Type = 224
	ImplementationSpecificEnd    Type = 240
	ReservedStart                Type = 241
	ReservedEnd                  Type = 254
)
